### ISSUE TITLE
Нужно дополнить .htaccess-ом 

### ISSUE THREAD

**Issue by everbslab** [2gis/webapi-democlient#1]
Нужно дополнить .htaccess-ом репозитарий поскольку в конфиге у вас с реврайтом запросов на index.php:

```
'components' => array(
    'urlManager' => array(
        'urlFormat' => 'path',
        'showScriptName' => false,
```

...

для большей совместимости и быстрого запуска новичков

.htaccess
---cut---
AddDefaultCharset UTF-8
DirectoryIndex index.php
Options +FollowSymLinks
IndexIgnore _/_
RewriteEngine on

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . index.php
---cut---

**Comment by ghost** [comment]
при попытке сделать запрос получаю Not Found The requested URL /search was not found on this server. Как это можно исправить?
